
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "safe-transaction.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-transaction.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
data:
  DOCKER_SHARED_DIR: "/nginx"
  PYTHONPATH: /app/
  DJANGO_SETTINGS_MODULE: config.settings.production
  DEBUG: "{{- .Values.config.debug }}"
  ETH_L2_NETWORK: "{{- .Values.config.ethL2Network }}"
  ETHEREUM_NODE_URL: "{{- .Values.config.ethereumRpcUrl }}"
  ETHEREUM_TRACING_NODE_URL: "{{- .Values.config.ethereumRpcUrl }}"
  DJANGO_ALLOWED_HOSTS: "{{- .Values.config.django.allowedHosts }}"
  FORCE_SCRIPT_NAME: "/"
  {{- if .Values.config.extraEnvVars }}
  {{ .Values.config.extraEnvVars | toYaml | nindent 2 }}
  {{- end }}
