---
{{- if not .Values.config.redis.secretReferenceKey  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-transaction.fullname" . }}-redis
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-transaction.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  password: .Values.config.redis.password
  REDIS_URL: "{{- printf "redis://%s:%s@%s:%s/%s" .Values.config.redis.username .Values.config.redis.password .Values.config.redis.host .Values.config.redis.port .Values.config.redis.database | b64enc -}}"
{{- end }}
