---
{{- if not .Values.config.rabbitmq.secretReferenceKey  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-transaction.fullname" . }}-rabbitmq
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-transaction.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  CELERY_BROKER_URL: "{{- printf "amqp://%s:%s@%s/%s" .Values.config.rabbitmq.username .Values.config.rabbitmq.password .Values.config.rabbitmq.host .Values.config.rabbitmq.virtualHost | b64enc -}}"
{{- end }}
