---
{{- if not .Values.config.postgres.secretReferenceKey  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-transaction.fullname" . }}-postgres
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-transaction.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  DATABASE_URL: "{{- printf "psql://%s:%s@%s:%s/%s" .Values.config.postgres.username .Values.config.postgres.password .Values.config.postgres.host .Values.config.postgres.port .Values.config.postgres.database | b64enc -}}"
{{- end }}
