{{- if not .Values.config.secretReferenceKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-transaction.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-transaction.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.config.secretKey | b64enc }}
{{- end }}
